<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>FastDelete.Shell</AssemblyName>
    <RootNamespace>FastDelete.Shell</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ComVisible>true</ComVisible>
    <EnableDynamicComInterop>true</EnableDynamicComInterop>
    <ComInterfaceAttributeGenerator></ComInterfaceAttributeGenerator>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
</Project>
